version: "3.6"
services:
  iris:
    build: .
    restart: always
    command: --check-caps false --ISCAgent false
    ports:
      - 51773
      - 52777:52773
      - 53773
    volumes:
      - ./:/irisdev/app
